Repository AdvisorySG/mentorship-page, pull requests merged in 2020-06, with the labels that each got.

#146 Header: Add sample application response
  src/components/header.jsx
Labels: enhancement

#153 Mentors: Hotfix 3.2
  data/csv/wave2.csv
  data/profile_images/CharlesTey.jpg
  data/profile_images/JohnLim.jpg
Labels: enhancement

#156 Mentors: Hotfix 3.4
  data/profile_images/AlexLoh.jpg
  data/profile_images/ChengHuiSng.jpg
  data/profile_images/HazelPeh.jpg
Labels: enhancement

#157 Mentors: Hotfix 3.5
  data/csv/wave0.csv
  data/csv/wave1.csv
  data/csv/wave2.csv
  scripts/process_mentors.py
Labels: enhancement

#163 Ensure modal opens on load if there is a URL hash.
  src/App.js
Labels: bug

#105 README.md: Add instructions for installing Python dependencies
  README.md
Labels: documentation
