Repository AdvisorySG/mentorship-page, pull requests merged in 2020-04, with the labels that each got.

#24 ProfileCards: Desktop flexbox adjustments
  src/App.css
  src/components/profile-card.css
  src/components/profile-card.jsx
Labels: enhancement

#23 Housekeeping: Rename className to prevent namespace conflicts
  src/App.css
  src/App.js
  src/components/header.css
  src/components/header.jsx
  src/components/profile-card.css
  src/components/profile-card.jsx
  src/components/profile-modal.css
  src/components/profile-modal.jsx
Labels: enhancement

#25 Header: Add text and mentorship logo
  src/assets/advisory-mentorship-logo.png
  src/assets/index.js
  src/components/header.css
  src/components/header.jsx
Labels: enhancement

#33 Allow modal to be closed upon clicking outside.
  src/components/profile-modal.jsx
  src/index.js
Labels: enhancement

#31 Use react-modal
  package-lock.json
  package.json
  src/App.js
  src/components/profile-modal.css
  src/components/profile-modal.jsx
  src/index.js
Labels: bug, enhancement

#46 ProfileCard: Restrict cards to fixed width based on viewport
  src/components/profile-card.css
Labels: bug

#44 Header: Have TypeForm link open in new tab
  src/components/header.jsx
Labels: bug

#47 Header: Expand intro text to 80% width
  src/components/header.css
Labels: enhancement

#67 Mentors Hotfix #1
  scripts/mentors.csv
  scripts/process_mentors.py
  src/mentors.json
Labels: bug

#61 Have conditional rendering for organization
  src/components/profile-card.jsx
  src/components/profile-modal.jsx
Labels: bug

#57 Search: Use react-autosuggest with Fuse.js for field search
  package-lock.json
  package.json
  src/App.js
  src/components/header.css
  src/components/header.jsx
  src/components/search-bar.css
  src/components/search-bar.jsx
  src/search.js
Labels: enhancement

#75 Mentors: Hotfix #4
  scripts/mentors.csv
  src/mentors.json
Labels: bug

#76 Mentors: Hotfix #5
  scripts/mentors.csv
  src/mentors.json
Labels: bug
